cargo-features = ["profile-rustflags"]

[features]
benchmarking = []

[package]
name = "flexalign"
version = "0.1.0"
edition = "2021"
channel = "nightly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kmerrs = { git = "https://github.com/4less/kmerr.git" }
flexmap = { git = "https://github.com/4less/flexmap.git", branch = "zeroable_load" }
bioreader = { git = "https://github.com/4less/bioreader.git" }
libwfa2 = "0.1.1"
clap = { version = "4.5.3", features = ["derive", "wrap_help"] }
clap_derive = "4.5.3"
flate2 = "1.0.28"
gzp = "0.11.3"
savefile = { version="0.17", feature="derive" }
savefile-derive = "0.17"
popcnt = "0.1.0"
colored = "2.1.0"
anstyle = "1.0.8"
glidesort = { version="0.1.2", feature="unstable" }
serde = { version = "1.0.207", features = ["derive"] }
serde_derive = "1.0.207"
bincode = { version = "2.0.0-rc.3" }
textplots = "0.8.6"
rgb = "0.8.48"
micromap = "0.0.15"
ser_raw = "0.1.0"
triple_accel = "0.4.0"
thiserror = "1.0.64"
simple_logger=  { version = "3", features = ["stderr"] }
log = "0"
itertools = "0.13.0"
stats = "0.0.1"
derive_builder = "0.20.2"


[profile.release]
opt-level = 3               # Use best optimizations
overflow-checks = false     # Disable integer overflow checks.
rustflags = ["-C", "target-feature=+avx,+sse3,+avx2,+fma"]#
lto = "fat"
